#ifndef ARENA_RUSSIAN_TRANSLATOR_HPP
#define ARENA_RUSSIAN_TRANSLATOR_HPP

#include <QHash>
#include <QLocale>
#include <QString>
#include <QTranslator>

namespace ArenaUi
{
    inline bool useRussianSystemUi()
    {
        return QLocale::system().language() == QLocale::Russian;
    }

    class RussianTranslator final : public QTranslator
    {
    public:
        QString translate(const char*, const char* sourceText, const char* = nullptr, int = -1) const override
        {
            if (sourceText == nullptr)
                return QString();
            const QString source = QString::fromUtf8(sourceText);
            const auto& map = translations();
            const auto it = map.constFind(source);
            return it == map.constEnd() ? QString() : it.value();
        }

    private:
        static const QHash<QString, QString>& translations()
        {
            static const QHash<QString, QString> map = []()
            {
                QHash<QString, QString> m;
                m.insert(QString::fromUtf8(u8"Play"), QString::fromUtf8(u8"Играть"));
                m.insert(QString::fromUtf8(u8"Data Files"), QString::fromUtf8(u8"Файлы данных"));
                m.insert(QString::fromUtf8(u8"Graphics"), QString::fromUtf8(u8"Графика"));
                m.insert(QString::fromUtf8(u8"Settings"), QString::fromUtf8(u8"Настройки"));
                m.insert(QString::fromUtf8(u8"Advanced"), QString::fromUtf8(u8"Дополнительно"));
                m.insert(QString::fromUtf8(u8"Help"), QString::fromUtf8(u8"Справка"));
                m.insert(QString::fromUtf8(u8"Close"), QString::fromUtf8(u8"Закрыть"));
                m.insert(QString::fromUtf8(u8"Save"), QString::fromUtf8(u8"Сохранить"));
                m.insert(QString::fromUtf8(u8"Reload"), QString::fromUtf8(u8"Перезагрузить"));
                m.insert(QString::fromUtf8(u8"Delete"), QString::fromUtf8(u8"Удалить"));
                m.insert(QString::fromUtf8(u8"Skip"), QString::fromUtf8(u8"Пропустить"));
                m.insert(QString::fromUtf8(u8"Host mode"), QString::fromUtf8(u8"Режим хоста"));
                m.insert(QString::fromUtf8(u8"Auto restart and backup"), QString::fromUtf8(u8"Автоперезапуск и резервная копия"));
                m.insert(QString::fromUtf8(u8"Enforce required data files"), QString::fromUtf8(u8"Проверять обязательные файлы данных"));
                m.insert(QString::fromUtf8(u8"Enforce required DataFiles"), QString::fromUtf8(u8"Проверять обязательные DataFiles"));
                m.insert(QString::fromUtf8(u8"Update Hash"), QString::fromUtf8(u8"Обновить хеши"));
                m.insert(QString::fromUtf8(u8"Run Server"), QString::fromUtf8(u8"Запустить сервер"));
                m.insert(QString::fromUtf8(u8"Stop Server"), QString::fromUtf8(u8"Остановить сервер"));
                m.insert(QString::fromUtf8(u8"Server Console"), QString::fromUtf8(u8"Консоль сервера"));
                m.insert(QString::fromUtf8(u8"Server Settings"), QString::fromUtf8(u8"Настройки сервера"));
                m.insert(QString::fromUtf8(u8"Clear Log"), QString::fromUtf8(u8"Очистить лог"));
                m.insert(QString::fromUtf8(u8"TES3MP Server"), QString::fromUtf8(u8"Сервер TES3MP"));
                m.insert(QString::fromUtf8(u8"Server Address:"), QString::fromUtf8(u8"Адрес сервера:"));
                m.insert(QString::fromUtf8(u8"Address for players:"), QString::fromUtf8(u8"Адрес для игроков:"));
                m.insert(QString::fromUtf8(u8"Port:"), QString::fromUtf8(u8"Порт:"));
                m.insert(QString::fromUtf8(u8"Build name:"), QString::fromUtf8(u8"Название сборки:"));
                m.insert(QString::fromUtf8(u8"Server network interface:"), QString::fromUtf8(u8"Сетевой интерфейс сервера:"));
                m.insert(QString::fromUtf8(u8"Refresh"), QString::fromUtf8(u8"Обновить"));
                m.insert(QString::fromUtf8(u8"All interfaces (recommended) - 0.0.0.0"), QString::fromUtf8(u8"Все интерфейсы (рекомендуется) - 0.0.0.0"));
                m.insert(QString::fromUtf8(u8"Local only - 127.0.0.1"), QString::fromUtf8(u8"Только локально - 127.0.0.1"));
                m.insert(QString::fromUtf8(u8"Unavailable interface - %1"), QString::fromUtf8(u8"Недоступный интерфейс - %1"));
                m.insert(QString::fromUtf8(u8"Server mode:"), QString::fromUtf8(u8"Режим сервера:"));
                m.insert(QString::fromUtf8(u8"CO-OP"), QString::fromUtf8(u8"CO-OP"));
                m.insert(QString::fromUtf8(u8"MMO"), QString::fromUtf8(u8"MMO"));
                m.insert(QString::fromUtf8(u8"Clear server cells"), QString::fromUtf8(u8"Очистить ячейки"));
                m.insert(QString::fromUtf8(u8"Full server reset"), QString::fromUtf8(u8"Полный сброс сервера"));
                m.insert(QString::fromUtf8(u8"Clear cells"), QString::fromUtf8(u8"Очистить ячейки"));
                m.insert(QString::fromUtf8(u8"Reset server"), QString::fromUtf8(u8"Сбросить сервер"));
                m.insert(QString::fromUtf8(u8"Connect to vanilla-build server"), QString::fromUtf8(u8"Подключаться к vanilla-серверу"));
                m.insert(QString::fromUtf8(u8"Hide chat messages"), QString::fromUtf8(u8"Скрывать сообщения чата"));
                m.insert(QString::fromUtf8(u8"Hide received chat messages while keeping the chat input available."), QString::fromUtf8(u8"Скрывать полученные сообщения чата, сохраняя возможность ввода."));
                m.insert(QString::fromUtf8(u8"Server language"), QString::fromUtf8(u8"Язык сервера"));
                m.insert(QString::fromUtf8(u8"Auto (client language)"), QString::fromUtf8(u8"Авто (язык клиента)"));
                m.insert(QString::fromUtf8(u8"English"), QString::fromUtf8(u8"English"));
                m.insert(QString::fromUtf8(u8"Russian"), QString::fromUtf8(u8"Русский"));
                m.insert(QString::fromUtf8(u8"Русский"), QString::fromUtf8(u8"Русский"));
                m.insert(QString::fromUtf8(u8"Game mode"), QString::fromUtf8(u8"Режим игры"));
                m.insert(QString::fromUtf8(u8"General"), QString::fromUtf8(u8"Общие"));
                m.insert(QString::fromUtf8(u8"Network and authority"), QString::fromUtf8(u8"Сеть и авторитет"));
                m.insert(QString::fromUtf8(u8"Shared progress"), QString::fromUtf8(u8"Общий прогресс"));
                m.insert(QString::fromUtf8(u8"Time and world"), QString::fromUtf8(u8"Время и мир"));
                m.insert(QString::fromUtf8(u8"Spawn and respawn"), QString::fromUtf8(u8"Появление и возрождение"));
                m.insert(QString::fromUtf8(u8"Player permissions"), QString::fromUtf8(u8"Права игроков"));
                m.insert(QString::fromUtf8(u8"Collision"), QString::fromUtf8(u8"Коллизии"));
                m.insert(QString::fromUtf8(u8"Rendering"), QString::fromUtf8(u8"Рендеринг"));
                m.insert(QString::fromUtf8(u8"Game Mechanics"), QString::fromUtf8(u8"Игровая механика"));
                m.insert(QString::fromUtf8(u8"Login time (sec)"), QString::fromUtf8(u8"Время на вход (сек)"));
                m.insert(QString::fromUtf8(u8"Max clients per IP"), QString::fromUtf8(u8"Макс. клиентов с одного IP"));
                m.insert(QString::fromUtf8(u8"Difficulty"), QString::fromUtf8(u8"Сложность"));
                m.insert(QString::fromUtf8(u8"Data path"), QString::fromUtf8(u8"Путь данных"));
                m.insert(QString::fromUtf8(u8"Database type"), QString::fromUtf8(u8"Тип базы данных"));
                m.insert(QString::fromUtf8(u8"Pass time when empty"), QString::fromUtf8(u8"Продолжать время без игроков"));
                m.insert(QString::fromUtf8(u8"Night starts at hour"), QString::fromUtf8(u8"Начало ночи"));
                m.insert(QString::fromUtf8(u8"Night ends at hour"), QString::fromUtf8(u8"Конец ночи"));
                m.insert(QString::fromUtf8(u8"Allow console"), QString::fromUtf8(u8"Разрешить консоль"));
                m.insert(QString::fromUtf8(u8"Allow bed rest"), QString::fromUtf8(u8"Разрешить отдых в кровати"));
                m.insert(QString::fromUtf8(u8"Allow wilderness rest"), QString::fromUtf8(u8"Разрешить отдых на природе"));
                m.insert(QString::fromUtf8(u8"Allow wait"), QString::fromUtf8(u8"Разрешить ожидание"));
                m.insert(QString::fromUtf8(u8"Journal"), QString::fromUtf8(u8"Журнал"));
                m.insert(QString::fromUtf8(u8"Faction ranks"), QString::fromUtf8(u8"Ранги фракций"));
                m.insert(QString::fromUtf8(u8"Faction expulsion"), QString::fromUtf8(u8"Исключение из фракций"));
                m.insert(QString::fromUtf8(u8"Faction reputation"), QString::fromUtf8(u8"Репутация фракций"));
                m.insert(QString::fromUtf8(u8"Dialogue topics"), QString::fromUtf8(u8"Темы диалогов"));
                m.insert(QString::fromUtf8(u8"Bounty"), QString::fromUtf8(u8"Штраф"));
                m.insert(QString::fromUtf8(u8"Reputation"), QString::fromUtf8(u8"Репутация"));
                m.insert(QString::fromUtf8(u8"Map exploration"), QString::fromUtf8(u8"Открытие карты"));
                m.insert(QString::fromUtf8(u8"Videos"), QString::fromUtf8(u8"Видеоролики"));
                m.insert(QString::fromUtf8(u8"Kills"), QString::fromUtf8(u8"Убийства"));
                m.insert(QString::fromUtf8(u8"Instanced spawn"), QString::fromUtf8(u8"Раздельная стартовая ячейка"));
                m.insert(QString::fromUtf8(u8"Players respawn on death"), QString::fromUtf8(u8"Возрождение игроков после смерти"));
                m.insert(QString::fromUtf8(u8"Respawn at Imperial shrine"), QString::fromUtf8(u8"Возрождение у имперского алтаря"));
                m.insert(QString::fromUtf8(u8"Respawn at Tribunal temple"), QString::fromUtf8(u8"Возрождение у храма Трибунала"));
                m.insert(QString::fromUtf8(u8"Reset bounty on death"), QString::fromUtf8(u8"Сбрасывать штраф после смерти"));
                m.insert(QString::fromUtf8(u8"Jail time based on bounty"), QString::fromUtf8(u8"Срок заключения зависит от штрафа"));
                m.insert(QString::fromUtf8(u8"Allow /suicide"), QString::fromUtf8(u8"Разрешить /suicide"));
                m.insert(QString::fromUtf8(u8"Allow /fixme"), QString::fromUtf8(u8"Разрешить /fixme"));
                m.insert(QString::fromUtf8(u8"/fixme cooldown (sec)"), QString::fromUtf8(u8"Задержка /fixme (сек)"));
                m.insert(QString::fromUtf8(u8"Player collision"), QString::fromUtf8(u8"Коллизия игроков"));
                m.insert(QString::fromUtf8(u8"Actor collision"), QString::fromUtf8(u8"Коллизия NPC"));
                m.insert(QString::fromUtf8(u8"Placed object collision"), QString::fromUtf8(u8"Коллизия размещённых объектов"));
                m.insert(QString::fromUtf8(u8"Actor-style for placed objects"), QString::fromUtf8(u8"Коллизия объектов как у NPC"));
                m.insert(QString::fromUtf8(u8"Container in unloaded cells"), QString::fromUtf8(u8"Контейнеры в незагруженных ячейках"));
                m.insert(QString::fromUtf8(u8"Ignore script errors"), QString::fromUtf8(u8"Игнорировать ошибки скриптов"));
                m.insert(QString::fromUtf8(u8"Log level"), QString::fromUtf8(u8"Уровень логов"));
                m.insert(QString::fromUtf8(u8"Physics framerate"), QString::fromUtf8(u8"Частота физики"));
                m.insert(QString::fromUtf8(u8"Authority ping difference"), QString::fromUtf8(u8"Разница пинга для авторитета"));
                m.insert(QString::fromUtf8(u8"ArenaMP NPC and combat mechanics"), QString::fromUtf8(u8"Механики NPC и боя ArenaMP"));
                m.insert(QString::fromUtf8(u8"Tactical NPC combat"), QString::fromUtf8(u8"Тактический бой NPC"));
                m.insert(QString::fromUtf8(u8"Weapon sheathe delay"), QString::fromUtf8(u8"Задержка убирания оружия"));
                m.insert(QString::fromUtf8(u8"Hostile NPC pursuit through doors"), QString::fromUtf8(u8"Преследование через двери"));
                m.insert(QString::fromUtf8(u8"Guaranteed distance"), QString::fromUtf8(u8"Гарантированная дистанция"));
                m.insert(QString::fromUtf8(u8"Door maximum distance"), QString::fromUtf8(u8"Макс. дистанция до двери"));
                m.insert(QString::fromUtf8(u8"Minimum pursuit chance"), QString::fromUtf8(u8"Мин. шанс преследования"));
                m.insert(QString::fromUtf8(u8"Maximum door pursuers"), QString::fromUtf8(u8"Макс. преследователей"));
                m.insert(QString::fromUtf8(u8"Same-cell pursuit leash"), QString::fromUtf8(u8"Макс. дистанция преследования"));
                m.insert(QString::fromUtf8(u8"Followers defend immediately"), QString::fromUtf8(u8"Спутники защищают сразу"));
                m.insert(QString::fromUtf8(u8"NPCs avoid collisions"), QString::fromUtf8(u8"NPC избегают столкновений"));
                m.insert(QString::fromUtf8(u8"NPCs give way"), QString::fromUtf8(u8"NPC уступают дорогу"));
                m.insert(QString::fromUtf8(u8"Allow NPC following over water"), QString::fromUtf8(u8"NPC могут следовать по воде"));
                m.insert(QString::fromUtf8(u8"Actor processing range"), QString::fromUtf8(u8"Дальность обработки NPC"));
                m.insert(QString::fromUtf8(u8"Loot during death animation"), QString::fromUtf8(u8"Можно обыскивать во время анимации смерти"));
                m.insert(QString::fromUtf8(u8"Weapon sheathing"), QString::fromUtf8(u8"Убирать оружие"));
                m.insert(QString::fromUtf8(u8"Shield sheathing"), QString::fromUtf8(u8"Убирать щит"));
                m.insert(QString::fromUtf8(u8"Graphic herbalism"), QString::fromUtf8(u8"Графический сбор растений"));
                m.insert(QString::fromUtf8(u8"Long blades use Agility scaling"), QString::fromUtf8(u8"Длинные клинки используют Ловкость"));
                m.insert(QString::fromUtf8(u8"Two-handed accuracy penalty"), QString::fromUtf8(u8"Штраф точности двуручного оружия"));
                m.insert(QString::fromUtf8(u8"Staves use accuracy bonus"), QString::fromUtf8(u8"Посохи получают бонус точности"));
                m.insert(QString::fromUtf8(u8"Skill books have level limits"), QString::fromUtf8(u8"Ограничение книг навыков по уровню"));
                m.insert(QString::fromUtf8(u8"New constant-effect difficulty"), QString::fromUtf8(u8"Новая сложность постоянных эффектов"));
                m.insert(QString::fromUtf8(u8"Global XP multiplier"), QString::fromUtf8(u8"Множитель опыта"));
                m.insert(QString::fromUtf8(u8"Graphics Presets"), QString::fromUtf8(u8"Пресеты графики"));
                m.insert(QString::fromUtf8(u8"Quality preset"), QString::fromUtf8(u8"Пресет качества"));
                m.insert(QString::fromUtf8(u8"Apply preset to settings.cfg"), QString::fromUtf8(u8"Применить пресет к settings.cfg"));
                m.insert(QString::fromUtf8(u8"Save current as preset..."), QString::fromUtf8(u8"Сохранить текущие как пресет..."));
                m.insert(QString::fromUtf8(u8"View distance"), QString::fromUtf8(u8"Дальность обзора"));
                m.insert(QString::fromUtf8(u8"Texture filter"), QString::fromUtf8(u8"Фильтрация текстур"));
                m.insert(QString::fromUtf8(u8"Nearest"), QString::fromUtf8(u8"Ближайшая"));
                m.insert(QString::fromUtf8(u8"Bilinear"), QString::fromUtf8(u8"Билинейная"));
                m.insert(QString::fromUtf8(u8"Trilinear"), QString::fromUtf8(u8"Трилинейная"));
                m.insert(QString::fromUtf8(u8"Anisotropic filter"), QString::fromUtf8(u8"Анизотропная фильтрация"));
                m.insert(QString::fromUtf8(u8"Lighting"), QString::fromUtf8(u8"Освещение"));
                m.insert(QString::fromUtf8(u8"Lighting method"), QString::fromUtf8(u8"Метод освещения"));
                m.insert(QString::fromUtf8(u8"Max lights per object"), QString::fromUtf8(u8"Макс. источников света на объект"));
                m.insert(QString::fromUtf8(u8"Shadows"), QString::fromUtf8(u8"Тени"));
                m.insert(QString::fromUtf8(u8"Enable shadows"), QString::fromUtf8(u8"Включить тени"));
                m.insert(QString::fromUtf8(u8"Actor shadows"), QString::fromUtf8(u8"Тени NPC"));
                m.insert(QString::fromUtf8(u8"Terrain shadows"), QString::fromUtf8(u8"Тени ландшафта"));
                m.insert(QString::fromUtf8(u8"Shadow map size"), QString::fromUtf8(u8"Размер карты теней"));
                m.insert(QString::fromUtf8(u8"Water and sky"), QString::fromUtf8(u8"Вода и небо"));
                m.insert(QString::fromUtf8(u8"Water shader"), QString::fromUtf8(u8"Шейдер воды"));
                m.insert(QString::fromUtf8(u8"Water reflection"), QString::fromUtf8(u8"Отражения воды"));
                m.insert(QString::fromUtf8(u8"Sunlight scattering"), QString::fromUtf8(u8"Рассеивание солнечного света"));
                m.insert(QString::fromUtf8(u8"Bloom / postprocess"), QString::fromUtf8(u8"Bloom / постобработка"));
                m.insert(QString::fromUtf8(u8"Shaders"), QString::fromUtf8(u8"Шейдеры"));
                m.insert(QString::fromUtf8(u8"Shaders (instanced)"), QString::fromUtf8(u8"Шейдеры (инстансинг)"));
                m.insert(QString::fromUtf8(u8"Use distance fog"), QString::fromUtf8(u8"Использовать дальний туман"));
                m.insert(QString::fromUtf8(u8"Radial fog"), QString::fromUtf8(u8"Радиальный туман"));
                m.insert(QString::fromUtf8(u8"Low"), QString::fromUtf8(u8"Низко"));
                m.insert(QString::fromUtf8(u8"Medium"), QString::fromUtf8(u8"Средне"));
                m.insert(QString::fromUtf8(u8"High"), QString::fromUtf8(u8"Высоко"));
                m.insert(QString::fromUtf8(u8"Ultra"), QString::fromUtf8(u8"Ультра"));
                m.insert(QString::fromUtf8(u8"Disabled"), QString::fromUtf8(u8"Отключено"));
                m.insert(QString::fromUtf8(u8"Legacy"), QString::fromUtf8(u8"Legacy"));
                m.insert(QString::fromUtf8(u8"Unlimited"), QString::fromUtf8(u8"Без ограничений"));
                m.insert(QString::fromUtf8(u8"Unknown"), QString::fromUtf8(u8"Неизвестно"));
                m.insert(QString::fromUtf8(u8"Unknown graphics adapter"), QString::fromUtf8(u8"Неизвестный графический адаптер"));
                m.insert(QString::fromUtf8(u8"Automatic recommendation: %1. "), QString::fromUtf8(u8"Автоматическая рекомендация: %1. "));
                m.insert(QString::fromUtf8(u8"Form"), QString::fromUtf8(u8"Форма"));
                m.insert(QString::fromUtf8(u8"Raw config.lua"), QString::fromUtf8(u8"Исходный config.lua"));
                m.insert(QString::fromUtf8(u8"Apply form -> raw config"), QString::fromUtf8(u8"Применить форму -> config"));
                m.insert(QString::fromUtf8(u8"Refresh form <- raw config"), QString::fromUtf8(u8"Обновить форму <- config"));
                m.insert(QString::fromUtf8(u8"Server settings editor"), QString::fromUtf8(u8"Редактор настроек сервера"));
                m.insert(QString::fromUtf8(u8"Loaded persistent server settings"), QString::fromUtf8(u8"Постоянные настройки сервера загружены"));
                m.insert(QString::fromUtf8(u8"Saved persistent server settings"), QString::fromUtf8(u8"Постоянные настройки сервера сохранены"));
                m.insert(QString::fromUtf8(u8"Form applied to raw config"), QString::fromUtf8(u8"Форма применена к config.lua"));
                m.insert(QString::fromUtf8(u8"Form synchronized to raw config"), QString::fromUtf8(u8"Форма синхронизирована с config.lua"));
                m.insert(QString::fromUtf8(u8"Raw config synchronized to form"), QString::fromUtf8(u8"config.lua синхронизирован с формой"));
                m.insert(QString::fromUtf8(u8"Form updated from raw config"), QString::fromUtf8(u8"Форма обновлена из config.lua"));
                m.insert(QString::fromUtf8(u8"Save error"), QString::fromUtf8(u8"Ошибка сохранения"));
                m.insert(QString::fromUtf8(u8"config.lua not found"), QString::fromUtf8(u8"config.lua не найден"));
                m.insert(QString::fromUtf8(u8"Could not open config.lua"), QString::fromUtf8(u8"Не удалось открыть config.lua"));
                m.insert(QString::fromUtf8(u8"No content files are selected."), QString::fromUtf8(u8"Не выбраны файлы content."));
                m.insert(QString::fromUtf8(u8"Selected data file was not found: %1"), QString::fromUtf8(u8"Выбранный файл данных не найден: %1"));
                m.insert(QString::fromUtf8(u8"Could not calculate CRC32 for %1"), QString::fromUtf8(u8"Не удалось вычислить CRC32 для %1"));
                m.insert(QString::fromUtf8(u8"Server manifest updated.\n\nRequired content: %1\nOptional groundcover: %2\n\n%3"), QString::fromUtf8(u8"Манифест сервера обновлён.\n\nОбязательные content: %1\nНеобязательные groundcover: %2\n\n%3"));
                m.insert(QString::fromUtf8(u8"Restart the server to apply the new manifest."), QString::fromUtf8(u8"Перезапустите сервер, чтобы применить новый манифест."));
                m.insert(QString::fromUtf8(u8"Clear server cells?"), QString::fromUtf8(u8"Очистить ячейки сервера?"));
                m.insert(QString::fromUtf8(u8"This will delete all saved cell state. Player accounts and world data will be kept. Continue?"), QString::fromUtf8(u8"Будут удалены все сохранённые состояния ячеек. Аккаунты игроков и данные мира сохранятся. Продолжить?"));
                m.insert(QString::fromUtf8(u8"All saved server cells were cleared."), QString::fromUtf8(u8"Все сохранённые ячейки сервера очищены."));
                m.insert(QString::fromUtf8(u8"Full server reset?"), QString::fromUtf8(u8"Полный сброс сервера?"));
                m.insert(QString::fromUtf8(u8"This will delete player accounts, cells, world state, maps, custom data, record stores and the server database. requiredDataFiles.json and banlist.json will be kept. Continue?"), QString::fromUtf8(u8"Будут удалены аккаунты игроков, ячейки, состояние мира, карты, пользовательские данные, хранилища записей и база сервера. requiredDataFiles.json и banlist.json сохранятся. Продолжить?"));
                m.insert(QString::fromUtf8(u8"Server gameplay data was fully reset."), QString::fromUtf8(u8"Игровые данные сервера полностью сброшены."));
                m.insert(QString::fromUtf8(u8"Stop the server before clearing persistent data."), QString::fromUtf8(u8"Перед очисткой постоянных данных остановите сервер."));
                m.insert(QString::fromUtf8(u8"Server data reset failed: %1"), QString::fromUtf8(u8"Не удалось очистить данные сервера: %1"));
                m.insert(QString::fromUtf8(u8"Log encoding:"), QString::fromUtf8(u8"Кодировка лога:"));
                m.insert(QString::fromUtf8(u8"System"), QString::fromUtf8(u8"Системная"));
                m.insert(QString::fromUtf8(u8"Windows-1251"), QString::fromUtf8(u8"Windows-1251"));
                m.insert(QString::fromUtf8(u8"CP866"), QString::fromUtf8(u8"CP866"));
                m.insert(QString::fromUtf8(u8"Starting tes3mp-server..."), QString::fromUtf8(u8"Запуск tes3mp-server..."));
                m.insert(QString::fromUtf8(u8"Stopping server..."), QString::fromUtf8(u8"Остановка сервера..."));
                m.insert(QString::fromUtf8(u8"Restarting server..."), QString::fromUtf8(u8"Перезапуск сервера..."));
                m.insert(QString::fromUtf8(u8"Server stopped. Exit code: %1"), QString::fromUtf8(u8"Сервер остановлен. Код выхода: %1"));
                m.insert(QString::fromUtf8(u8"Server crashed too many times in a short period. Auto restart disabled."), QString::fromUtf8(u8"Сервер слишком часто аварийно завершался. Автоперезапуск отключён."));
                m.insert(QString::fromUtf8(u8"Backup created: %1"), QString::fromUtf8(u8"Резервная копия создана: %1"));
                m.insert(QString::fromUtf8(u8"Backup failed: %1"), QString::fromUtf8(u8"Ошибка резервного копирования: %1"));
                m.insert(QString::fromUtf8(u8"Creating backup in background: %1"), QString::fromUtf8(u8"Создание резервной копии: %1"));
                m.insert(QString::fromUtf8(u8"Process error: %1"), QString::fromUtf8(u8"Ошибка процесса: %1"));
                m.insert(QString::fromUtf8(u8"Working directory: %1"), QString::fromUtf8(u8"Рабочая папка: %1"));
                m.insert(QString::fromUtf8(u8"Server config: %1"), QString::fromUtf8(u8"Конфигурация сервера: %1"));
                m.insert(QString::fromUtf8(u8"Server data: %1"), QString::fromUtf8(u8"Данные сервера: %1"));
                m.insert(QString::fromUtf8(u8"Connect IP: %1"), QString::fromUtf8(u8"IP подключения: %1"));
                m.insert(QString::fromUtf8(u8"Port: %1"), QString::fromUtf8(u8"Порт: %1"));
                m.insert(QString::fromUtf8(u8"Server did not stop in time; forcing termination..."), QString::fromUtf8(u8"Сервер не остановился вовремя; принудительное завершение..."));
                m.insert(QString::fromUtf8(u8"Error preparing ArenaMP server"), QString::fromUtf8(u8"Ошибка подготовки сервера ArenaMP"));
                m.insert(QString::fromUtf8(u8"Error starting executable"), QString::fromUtf8(u8"Ошибка запуска исполняемого файла"));
                m.insert(QString::fromUtf8(u8"OpenMW Wizard"), QString::fromUtf8(u8"Мастер ArenaMW"));
                m.insert(QString::fromUtf8(u8"Welcome to the OpenMW Wizard"), QString::fromUtf8(u8"Добро пожаловать в мастер ArenaMW"));
                m.insert(QString::fromUtf8(u8"This Wizard will help you install Morrowind and its add-ons for OpenMW to use."), QString::fromUtf8(u8"Этот мастер поможет настроить Morrowind и дополнения для ArenaMW."));
                m.insert(QString::fromUtf8(u8"Select Installation Method"), QString::fromUtf8(u8"Выберите способ установки"));
                m.insert(QString::fromUtf8(u8"Existing Installation"), QString::fromUtf8(u8"Существующая установка"));
                m.insert(QString::fromUtf8(u8"Select an existing installation."), QString::fromUtf8(u8"Выбрать существующую установку."));
                m.insert(QString::fromUtf8(u8"Retail CD/DVD"), QString::fromUtf8(u8"CD/DVD издание"));
                m.insert(QString::fromUtf8(u8"Install from a retail disc to a new location."), QString::fromUtf8(u8"Установить игру с диска в новую папку."));
                m.insert(QString::fromUtf8(u8"Don't have a copy?"), QString::fromUtf8(u8"Нет копии игры?"));
                m.insert(QString::fromUtf8(u8"Buy the game"), QString::fromUtf8(u8"Купить игру"));
                m.insert(QString::fromUtf8(u8"Select Data Files Folder"), QString::fromUtf8(u8"Выберите папку Data Files"));
                m.insert(QString::fromUtf8(u8"Detected or selected Data Files folders:"), QString::fromUtf8(u8"Найденные или выбранные папки Data Files:"));
                m.insert(QString::fromUtf8(u8"Select a Data Files folder to scan its base masters and BSA archives."), QString::fromUtf8(u8"Выберите папку Data Files для поиска базовых ESM и BSA."));
                m.insert(QString::fromUtf8(u8"Browse..."), QString::fromUtf8(u8"Обзор..."));
                m.insert(QString::fromUtf8(u8"Select the folder that contains your ESM and BSA files. Base game files are detected and enabled automatically."), QString::fromUtf8(u8"Выберите папку с ESM и BSA. Базовые файлы игры будут найдены и включены автоматически."));
                m.insert(QString::fromUtf8(u8"Select Morrowind Language"), QString::fromUtf8(u8"Выберите язык Morrowind"));
                m.insert(QString::fromUtf8(u8"Select the language of the Morrowind installation."), QString::fromUtf8(u8"Выберите язык установленного Morrowind."));
                m.insert(QString::fromUtf8(u8"What is the language of the Morrowind installation?"), QString::fromUtf8(u8"Какой язык у установленного Morrowind?"));
                m.insert(QString::fromUtf8(u8"Select Components"), QString::fromUtf8(u8"Выберите компоненты"));
                m.insert(QString::fromUtf8(u8"Which components should be installed?"), QString::fromUtf8(u8"Какие компоненты установить?"));
                m.insert(QString::fromUtf8(u8"Select which official Morrowind expansions should be installed. For best results, it is recommended to have both expansions installed."), QString::fromUtf8(u8"Выберите официальные дополнения Morrowind. Рекомендуется установить оба."));
                m.insert(QString::fromUtf8(u8"Morrowind"), QString::fromUtf8(u8"Morrowind"));
                m.insert(QString::fromUtf8(u8"Tribunal"), QString::fromUtf8(u8"Tribunal"));
                m.insert(QString::fromUtf8(u8"Bloodmoon"), QString::fromUtf8(u8"Bloodmoon"));
                m.insert(QString::fromUtf8(u8"Select Installation Destination"), QString::fromUtf8(u8"Выберите папку установки"));
                m.insert(QString::fromUtf8(u8"Where should Morrowind be installed?"), QString::fromUtf8(u8"Куда установить Morrowind?"));
                m.insert(QString::fromUtf8(u8"Morrowind will be installed to the following location. "), QString::fromUtf8(u8"Morrowind будет установлен в следующую папку. "));
                m.insert(QString::fromUtf8(u8"Import Settings"), QString::fromUtf8(u8"Импорт настроек"));
                m.insert(QString::fromUtf8(u8"Import settings from Morrowind.ini"), QString::fromUtf8(u8"Импортировать настройки из Morrowind.ini"));
                m.insert(QString::fromUtf8(u8"Import add-on and plugin selection"), QString::fromUtf8(u8"Импортировать выбор дополнений и плагинов"));
                m.insert(QString::fromUtf8(u8"Optionally import legacy settings when Morrowind.ini is available."), QString::fromUtf8(u8"При наличии Morrowind.ini можно импортировать старые настройки."));
                m.insert(QString::fromUtf8(u8"Installing"), QString::fromUtf8(u8"Установка"));
                m.insert(QString::fromUtf8(u8"Please wait while Morrowind is installed on your computer."), QString::fromUtf8(u8"Подождите, пока Morrowind устанавливается."));
                m.insert(QString::fromUtf8(u8"Completing the OpenMW Wizard"), QString::fromUtf8(u8"Завершение мастера ArenaMW"));
                m.insert(QString::fromUtf8(u8"Installation completed successfully!"), QString::fromUtf8(u8"Установка успешно завершена!"));
                m.insert(QString::fromUtf8(u8"Installation failed!"), QString::fromUtf8(u8"Ошибка установки!"));
                m.insert(QString::fromUtf8(u8"Installation finished"), QString::fromUtf8(u8"Установка завершена"));
                m.insert(QString::fromUtf8(u8"Quit Wizard"), QString::fromUtf8(u8"Закрыть мастер"));
                m.insert(QString::fromUtf8(u8"Are you sure you want to exit the Wizard?"), QString::fromUtf8(u8"Вы действительно хотите выйти из мастера?"));
                m.insert(QString::fromUtf8(u8"&Install"), QString::fromUtf8(u8"&Установить"));
                m.insert(QString::fromUtf8(u8"&Skip"), QString::fromUtf8(u8"&Пропустить"));
                m.insert(QString::fromUtf8(u8"Re-install &Bloodmoon"), QString::fromUtf8(u8"Переустановить &Bloodmoon"));
                m.insert(QString::fromUtf8(u8"Select the Morrowind Data Files folder"), QString::fromUtf8(u8"Выберите папку Morrowind Data Files"));
                m.insert(QString::fromUtf8(u8"Invalid Data Files folder"), QString::fromUtf8(u8"Неверная папка Data Files"));
                m.insert(QString::fromUtf8(u8"The selected Data Files folder does not exist or is not a directory."), QString::fromUtf8(u8"Выбранная папка Data Files не существует или не является папкой."));
                m.insert(QString::fromUtf8(u8"No existing Data Files folders detected"), QString::fromUtf8(u8"Папки Data Files не найдены"));
                m.insert(QString::fromUtf8(u8"Destination not empty"), QString::fromUtf8(u8"Папка назначения не пуста"));
                m.insert(QString::fromUtf8(u8"Insufficient permissions"), QString::fromUtf8(u8"Недостаточно прав"));
                m.insert(QString::fromUtf8(u8"An error occurred"), QString::fromUtf8(u8"Произошла ошибка"));
                m.insert(QString::fromUtf8(u8"Error creating destination"), QString::fromUtf8(u8"Ошибка создания папки назначения"));
                m.insert(QString::fromUtf8(u8"Could not create build.ini"), QString::fromUtf8(u8"Не удалось создать build.ini"));
                m.insert(QString::fromUtf8(u8"Preserved existing build manifest without changes: %1"), QString::fromUtf8(u8"Существующий манифест сборки сохранён без изменений: %1"));
                m.insert(QString::fromUtf8(u8"Saved build manifest: %1"), QString::fromUtf8(u8"Манифест сборки сохранён: %1"));
                m.insert(QString::fromUtf8(u8"Loaded build manifest: %1"), QString::fromUtf8(u8"Манифест сборки загружен: %1"));
                m.insert(QString::fromUtf8(u8"Applied the exact language and plug-in order from build.ini."), QString::fromUtf8(u8"Применены точные язык и порядок плагинов из build.ini."));
                m.insert(QString::fromUtf8(u8"<html><head/><body><p>Select how you would like to install <i>The Elder Scrolls III: Morrowind</i>.</p></body></html>"), QString::fromUtf8(u8"<html><head/><body><p>Выберите способ установки <i>The Elder Scrolls III: Morrowind</i>.</p></body></html>"));
                m.insert(QString::fromUtf8(u8"<html><head/><body><p>Select which official Morrowind expansions should be installed. For best results, it is recommended to have both expansions installed.</p><p><span style=\" font-weight:bold;\">Note:</span> It is possible to install expansions later by re-running this Wizard.<br/></p></body></html>"), QString::fromUtf8(u8"<html><head/><body><p>Выберите официальные дополнения Morrowind. Рекомендуется установить оба.</p><p><span style=\" font-weight:bold;\">Примечание:</span> Дополнения можно установить позже, снова запустив мастер.<br/></p></body></html>"));
                m.insert(QString::fromUtf8(u8"<html><head/><body><p>Morrowind.ini import is optional. The selected Data Files folder, base masters and BSA archives are configured automatically.</p><p><span style=\" font-weight:bold;\">Note:</span> It is possible to import settings later by re-running this Wizard.</p><p/></body></html>"), QString::fromUtf8(u8"<html><head/><body><p>Импорт Morrowind.ini необязателен. Выбранная папка Data Files, базовые ESM и BSA настраиваются автоматически.</p><p><span style=\" font-weight:bold;\">Примечание:</span> Настройки можно импортировать позже, снова запустив мастер.</p><p/></body></html>"));
                m.insert(QString::fromUtf8(u8"Generate the server data-file manifest from the current Content Files order and CRC32 hashes."), QString::fromUtf8(u8"Создать серверный манифест по текущему порядку Content Files и их CRC32."));
                m.insert(QString::fromUtf8(u8"Reject clients whose required content list, order or CRC32 hashes do not match the server manifest."), QString::fromUtf8(u8"Отклонять клиентов, если список обязательных файлов, порядок или CRC32 не совпадают с манифестом сервера."));
                m.insert(QString::fromUtf8(u8"CO-OP shares story and progression between players. MMO keeps player progression separate while required world/actor networking remains enabled."), QString::fromUtf8(u8"CO-OP синхронизирует сюжет и прогресс игроков. MMO оставляет прогресс персональным, сохраняя обязательную сетевую синхронизацию мира и NPC."));
                m.insert(QString::fromUtf8(u8"Delete saved cell state while keeping player accounts and world data."), QString::fromUtf8(u8"Удалить сохранённые состояния ячеек, сохранив аккаунты игроков и данные мира."));
                m.insert(QString::fromUtf8(u8"Delete all persistent gameplay data. The data-file manifest and ban list are preserved."), QString::fromUtf8(u8"Удалить все постоянные игровые данные. Манифест файлов и список блокировок сохраняются."));
                m.insert(QString::fromUtf8(u8"Address you give to other players. It is not used as the server bind address. "), QString::fromUtf8(u8"Адрес, который вы сообщаете другим игрокам. Он не используется как bind-адрес сервера. "));
                m.insert(QString::fromUtf8(u8"Radmin/VPN IP or public IP (optional)"), QString::fromUtf8(u8"IP Radmin/VPN или внешний IP (необязательно)"));
                m.insert(QString::fromUtf8(u8"Invalid server interface"), QString::fromUtf8(u8"Неверный сетевой интерфейс сервера"));
                m.insert(QString::fromUtf8(u8"Invalid server port"), QString::fromUtf8(u8"Неверный порт сервера"));
                m.insert(QString::fromUtf8(u8"Server bind address must be a valid IPv4 address."), QString::fromUtf8(u8"Bind-адрес сервера должен быть корректным IPv4-адресом."));
                m.insert(QString::fromUtf8(u8"Online server - %1:%2"), QString::fromUtf8(u8"Сервер запущен - %1:%2"));
                m.insert(QString::fromUtf8(u8"Server stopped"), QString::fromUtf8(u8"Сервер остановлен"));
                m.insert(QString::fromUtf8(u8"Persistent: %1  ->  Runtime: %2"), QString::fromUtf8(u8"Постоянный: %1  ->  Рабочий: %2"));
                m.insert(QString::fromUtf8(u8"Port must be a number from 1 to 65535."), QString::fromUtf8(u8"Порт должен быть числом от 1 до 65535."));
                m.insert(QString::fromUtf8(u8"The build name is locked by build.ini (complete=true)."), QString::fromUtf8(u8"Название сборки заблокировано build.ini (complete=true)."));
                m.insert(QString::fromUtf8(u8"This value is locked by build.ini (complete=true)."), QString::fromUtf8(u8"Значение заблокировано build.ini (complete=true)."));
                m.insert(QString::fromUtf8(u8"First run"), QString::fromUtf8(u8"Первый запуск"));
                m.insert(QString::fromUtf8(u8"Run &Installation Wizard"), QString::fromUtf8(u8"Запустить &мастер установки"));
                m.insert(QString::fromUtf8(u8"Run &Installation Wizard..."), QString::fromUtf8(u8"Запустить &мастер установки..."));
                m.insert(QString::fromUtf8(u8"Importer finished"), QString::fromUtf8(u8"Импорт завершён"));
                m.insert(QString::fromUtf8(u8"No game file selected"), QString::fromUtf8(u8"Не выбран игровой файл"));
                m.insert(QString::fromUtf8(u8"New Content List"), QString::fromUtf8(u8"Новый список контента"));
                m.insert(QString::fromUtf8(u8"Clone Content List"), QString::fromUtf8(u8"Клонировать список контента"));
                m.insert(QString::fromUtf8(u8"Delete Content List"), QString::fromUtf8(u8"Удалить список контента"));
                m.insert(QString::fromUtf8(u8"Content List name:"), QString::fromUtf8(u8"Название списка контента:"));
                m.insert(QString::fromUtf8(u8"Could not remove server data: %1"), QString::fromUtf8(u8"Не удалось удалить данные сервера: %1"));
                m.insert(QString::fromUtf8(u8"Server preparation failed: %1"), QString::fromUtf8(u8"Ошибка подготовки сервера: %1"));
                m.insert(QString::fromUtf8(u8"Loaded settings, but could not synchronize the persistent/runtime copy: %1"), QString::fromUtf8(u8"Настройки загружены, но не удалось синхронизировать постоянную и рабочую копии: %1"));
                m.insert(QString::fromUtf8(u8"Custom mix of OSG Patch settings. Pick a preset and press Apply preset to overwrite the controls below."), QString::fromUtf8(u8"Пользовательский набор настроек OSG Patch. Выберите пресет и нажмите «Применить», чтобы заменить параметры ниже."));
                m.insert(QString::fromUtf8(u8"%1 logical threads, %2 MP primary display"), QString::fromUtf8(u8"%1 логических потоков, основной дисплей MP: %2"));
                m.insert(QString::fromUtf8(u8" (%1 MB dedicated VRAM)"), QString::fromUtf8(u8" (%1 МБ выделенной VRAM)"));
                m.insert(QString::fromUtf8(u8" - integrated"), QString::fromUtf8(u8" - встроенная"));
                m.insert(QString::fromUtf8(u8" - software renderer"), QString::fromUtf8(u8" - программный рендерер"));
                m.insert(QString::fromUtf8(u8"Error reading settings.cfg"), QString::fromUtf8(u8"Ошибка чтения settings.cfg"));
                m.insert(QString::fromUtf8(u8"Error writing settings.cfg"), QString::fromUtf8(u8"Ошибка записи settings.cfg"));
                m.insert(QString::fromUtf8(u8"Could not save the selected graphics preset:\n\n%1"), QString::fromUtf8(u8"Не удалось сохранить выбранный графический пресет:\n\n%1"));
                m.insert(QString::fromUtf8(u8"Could not reload the current game settings before applying the preset:\n\n%1"), QString::fromUtf8(u8"Не удалось перечитать текущие настройки игры перед применением пресета:\n\n%1"));
                m.insert(QString::fromUtf8(u8"Select configuration file"), QString::fromUtf8(u8"Выберите файл конфигурации"));
                m.insert(QString::fromUtf8(u8"Select script file"), QString::fromUtf8(u8"Выберите файл скрипта"));
                m.insert(QString::fromUtf8(u8"Text file (*.txt)"), QString::fromUtf8(u8"Текстовый файл (*.txt)"));
                m.insert(QString::fromUtf8(u8"Morrowind configuration file (*.ini)"), QString::fromUtf8(u8"Файл конфигурации Morrowind (*.ini)"));
                m.insert(QString::fromUtf8(u8"%1 Installation"), QString::fromUtf8(u8"Установка %1"));
                m.insert(QString::fromUtf8(u8"Select where to install Morrowind"), QString::fromUtf8(u8"Выберите папку установки Morrowind"));
                m.insert(QString::fromUtf8(u8"Selected components:"), QString::fromUtf8(u8"Выбранные компоненты:"));
                m.insert(QString::fromUtf8(u8"Base masters found: %1. BSA archives found: %2."), QString::fromUtf8(u8"Найдено базовых ESM: %1. Архивов BSA: %2."));
                m.insert(QString::fromUtf8(u8"Morrowind\t\t(installed)"), QString::fromUtf8(u8"Morrowind\t\t(установлен)"));
                m.insert(QString::fromUtf8(u8"Tribunal\t\t(installed)"), QString::fromUtf8(u8"Tribunal\t\t(установлен)"));
                m.insert(QString::fromUtf8(u8"Bloodmoon\t\t(installed)"), QString::fromUtf8(u8"Bloodmoon\t\t(установлен)"));
                m.insert(QString::fromUtf8(u8"none"), QString::fromUtf8(u8"нет"));
                m.insert(QString::fromUtf8(u8"Morrowind.ini was found. Importing legacy settings and plugin selection is optional; detected base ESM and BSA files are configured automatically in either case."), QString::fromUtf8(u8"Morrowind.ini найден. Импорт старых настроек и выбора плагинов необязателен; найденные базовые ESM и BSA в любом случае будут настроены автоматически."));
                m.insert(QString::fromUtf8(u8"Morrowind.ini was not found. This is allowed: the selected Data Files folder, existing base ESM files and all BSA archives will be configured directly."), QString::fromUtf8(u8"Morrowind.ini не найден. Это допустимо: выбранная папка Data Files, существующие базовые ESM и все BSA будут настроены напрямую."));
                m.insert(QString::fromUtf8(u8"No Morrowind.ini was found. Data Files, base masters and BSA archives were configured directly; INI import was skipped."), QString::fromUtf8(u8"Morrowind.ini не найден. Data Files, базовые ESM и BSA настроены напрямую; импорт INI пропущен."));
                m.insert(QString::fromUtf8(u8"build.ini detected: %1. Plugins: %2, groundcover: %3, BSA archives: %4, server: %5:%6. The stored order will be applied automatically."), QString::fromUtf8(u8"Найден build.ini: %1. Плагины: %2, groundcover: %3, BSA: %4, сервер: %5:%6. Сохранённый порядок будет применён автоматически."));
                m.insert(QString::fromUtf8(u8"build.ini exists but could not be loaded; no additional plug-ins were enabled."), QString::fromUtf8(u8"build.ini существует, но его не удалось загрузить; дополнительные плагины не включены."));
                m.insert(QString::fromUtf8(u8"Reapplied the new Wizard content, groundcover and archive order after Morrowind.ini import."), QString::fromUtf8(u8"После импорта Morrowind.ini повторно применён порядок content, groundcover и архивов из нового мастера."));
                m.insert(QString::fromUtf8(u8"The Morrowind.ini importer failed, but the new Wizard file order was restored before saving."), QString::fromUtf8(u8"Импорт Morrowind.ini завершился ошибкой, но перед сохранением порядок файлов нового мастера был восстановлен."));
                m.insert(QString::fromUtf8(u8"The game configuration was saved, but %1 could not be written.\n\n%2"), QString::fromUtf8(u8"Конфигурация игры сохранена, но %1 записать не удалось.\n\n%2"));
                m.insert(QString::fromUtf8(u8"Select %1 installation media"), QString::fromUtf8(u8"Выберите установочный носитель %1"));
                m.insert(QString::fromUtf8(u8"Attempting to install component %1."), QString::fromUtf8(u8"Установка компонента %1."));
                m.insert(QString::fromUtf8(u8"<p>Attempting to install component %1.</p>"), QString::fromUtf8(u8"<p>Установка компонента %1.</p>"));
                m.insert(QString::fromUtf8(u8"About to install Tribunal after Bloodmoon"), QString::fromUtf8(u8"Tribunal будет установлен после Bloodmoon"));
                m.insert(QString::fromUtf8(u8"Could not read %1: %2"), QString::fromUtf8(u8"Не удалось прочитать %1: %2"));
                m.insert(QString::fromUtf8(u8"Could not write %1: %2"), QString::fromUtf8(u8"Не удалось записать %1: %2"));
                m.insert(QString::fromUtf8(u8"Error opening Wizard log file"), QString::fromUtf8(u8"Ошибка открытия лога мастера"));
                m.insert(QString::fromUtf8(u8"Yes"), QString::fromUtf8(u8"Да"));
                m.insert(QString::fromUtf8(u8"No"), QString::fromUtf8(u8"Нет"));
                m.insert(QString::fromUtf8(u8"Cancel"), QString::fromUtf8(u8"Отмена"));
                m.insert(QString::fromUtf8(u8"Close"), QString::fromUtf8(u8"Закрыть"));
                m.insert(QString::fromUtf8(u8"Apply"), QString::fromUtf8(u8"Применить"));
                m.insert(QString::fromUtf8(u8"OK"), QString::fromUtf8(u8"OK"));
                m.insert(QString::fromUtf8(u8"&Next >"), QString::fromUtf8(u8"&Далее >"));
                m.insert(QString::fromUtf8(u8"< &Back"), QString::fromUtf8(u8"< &Назад"));
                m.insert(QString::fromUtf8(u8"&Finish"), QString::fromUtf8(u8"&Готово"));
                m.insert(QString::fromUtf8(u8"&Cancel"), QString::fromUtf8(u8"&Отмена"));
                m.insert(QString::fromUtf8(u8"Next"), QString::fromUtf8(u8"Далее"));
                m.insert(QString::fromUtf8(u8"Back"), QString::fromUtf8(u8"Назад"));
                m.insert(QString::fromUtf8(u8"Finish"), QString::fromUtf8(u8"Готово"));
                m.insert(QString::fromUtf8(u8"Death penalty jail days"), QString::fromUtf8(u8"Дней заключения за смерть"));
                m.insert(QString::fromUtf8(u8"Death time (sec)"), QString::fromUtf8(u8"Время смерти (сек)"));
                m.insert(QString::fromUtf8(u8"Server data directory"), QString::fromUtf8(u8"Папка данных сервера"));
                m.insert(QString::fromUtf8(u8"Enable ArenaMP strafing, circling, retreats, dodge jumps and stuck recovery while AiCombat stays active."), QString::fromUtf8(u8"Включить стрейфы, обход, отступления, уклонения и восстановление при застревании NPC ArenaMP, сохраняя активный AiCombat."));
                m.insert(QString::fromUtf8(u8"Use the official TES3MP 0.8.1 network identity (protocol 10, commit 68954091c5) required by older non-ArenaMP servers. Content files are not changed automatically, and local auto-start is skipped in this mode."), QString::fromUtf8(u8"Использовать официальную сетевую идентификацию TES3MP 0.8.1 для старых серверов без ArenaMP. Список контента автоматически не меняется, локальный автозапуск в этом режиме отключён."));
                m.insert(QString::fromUtf8(u8"AUTO uses each client's detected language. RU or EN forces one language for every server message."), QString::fromUtf8(u8"AUTO использует язык каждого клиента. RU или EN принудительно задают один язык всех серверных сообщений."));
                m.insert(QString::fromUtf8(u8"ArenaMP Launcher"), QString::fromUtf8(u8"Лаунчер ArenaMP"));
                m.insert(QString::fromUtf8(u8"Morrowind Installation Wizard"), QString::fromUtf8(u8"Мастер установки Morrowind"));
                m.insert(QString::fromUtf8(u8"Morrowind Settings Importer"), QString::fromUtf8(u8"Импорт настроек Morrowind"));
                m.insert(QString::fromUtf8(u8"Content"), QString::fromUtf8(u8"Контент"));
                m.insert(QString::fromUtf8(u8"Content List"), QString::fromUtf8(u8"Список контента"));
                m.insert(QString::fromUtf8(u8"Select a content list"), QString::fromUtf8(u8"Выберите список контента"));
                m.insert(QString::fromUtf8(u8"Refresh Data Files"), QString::fromUtf8(u8"Обновить файлы данных"));
                m.insert(QString::fromUtf8(u8"Check Selection"), QString::fromUtf8(u8"Отметить выбранное"));
                m.insert(QString::fromUtf8(u8"Uncheck Selection"), QString::fromUtf8(u8"Снять отметки"));
                m.insert(QString::fromUtf8(u8"&New Content List"), QString::fromUtf8(u8"&Новый список контента"));
                m.insert(QString::fromUtf8(u8"Audio"), QString::fromUtf8(u8"Аудио"));
                m.insert(QString::fromUtf8(u8"Audio Device"), QString::fromUtf8(u8"Аудиоустройство"));
                m.insert(QString::fromUtf8(u8"Interface"), QString::fromUtf8(u8"Интерфейс"));
                m.insert(QString::fromUtf8(u8"Display"), QString::fromUtf8(u8"Экран"));
                m.insert(QString::fromUtf8(u8"Resolution:"), QString::fromUtf8(u8"Разрешение:"));
                m.insert(QString::fromUtf8(u8"Screen:"), QString::fromUtf8(u8"Экран:"));
                m.insert(QString::fromUtf8(u8"Full Screen"), QString::fromUtf8(u8"Полный экран"));
                m.insert(QString::fromUtf8(u8"Window Border"), QString::fromUtf8(u8"Рамка окна"));
                m.insert(QString::fromUtf8(u8"Vertical Sync"), QString::fromUtf8(u8"Вертикальная синхронизация"));
                m.insert(QString::fromUtf8(u8"Framerate Limit:"), QString::fromUtf8(u8"Ограничение FPS:"));
                m.insert(QString::fromUtf8(u8"GUI scaling factor"), QString::fromUtf8(u8"Масштаб интерфейса"));
                m.insert(QString::fromUtf8(u8"Screenshot Format"), QString::fromUtf8(u8"Формат скриншота"));
                m.insert(QString::fromUtf8(u8"Maximum Quicksaves"), QString::fromUtf8(u8"Максимум быстрых сохранений"));
                m.insert(QString::fromUtf8(u8"Saves"), QString::fromUtf8(u8"Сохранения"));
                m.insert(QString::fromUtf8(u8"Camera"), QString::fromUtf8(u8"Камера"));
                m.insert(QString::fromUtf8(u8"Controls"), QString::fromUtf8(u8"Управление"));
                m.insert(QString::fromUtf8(u8"Visuals"), QString::fromUtf8(u8"Графика"));
                m.insert(QString::fromUtf8(u8"Animations"), QString::fromUtf8(u8"Анимации"));
                m.insert(QString::fromUtf8(u8"Bug Fixes"), QString::fromUtf8(u8"Исправления"));
                m.insert(QString::fromUtf8(u8"Miscellaneous"), QString::fromUtf8(u8"Прочее"));
                m.insert(QString::fromUtf8(u8"Testing helpers"), QString::fromUtf8(u8"Тестовые функции"));
                m.insert(QString::fromUtf8(u8"Graphics quality"), QString::fromUtf8(u8"Качество графики"));
                m.insert(QString::fromUtf8(u8"Preset:"), QString::fromUtf8(u8"Пресет:"));
                m.insert(QString::fromUtf8(u8"Presets"), QString::fromUtf8(u8"Пресеты"));
                m.insert(QString::fromUtf8(u8"Apply preset"), QString::fromUtf8(u8"Применить пресет"));
                m.insert(QString::fromUtf8(u8"Automatic"), QString::fromUtf8(u8"Автоматически"));
                m.insert(QString::fromUtf8(u8"Auto (recommended)"), QString::fromUtf8(u8"Авто (рекомендуется)"));
                m.insert(QString::fromUtf8(u8"Balanced"), QString::fromUtf8(u8"Сбалансировано"));
                m.insert(QString::fromUtf8(u8"Quality"), QString::fromUtf8(u8"Качество"));
                m.insert(QString::fromUtf8(u8"Max Performance"), QString::fromUtf8(u8"Макс. производительность"));
                m.insert(QString::fromUtf8(u8"Minimum"), QString::fromUtf8(u8"Минимум"));
                m.insert(QString::fromUtf8(u8"Maximum"), QString::fromUtf8(u8"Максимум"));
                m.insert(QString::fromUtf8(u8"Recommendation:"), QString::fromUtf8(u8"Рекомендация:"));
                m.insert(QString::fromUtf8(u8"Detected hardware"), QString::fromUtf8(u8"Обнаруженное оборудование"));
                m.insert(QString::fromUtf8(u8"Detect hardware again"), QString::fromUtf8(u8"Определить оборудование заново"));
                m.insert(QString::fromUtf8(u8"Graphics adapter:"), QString::fromUtf8(u8"Видеоадаптер:"));
                m.insert(QString::fromUtf8(u8"Processor:"), QString::fromUtf8(u8"Процессор:"));
                m.insert(QString::fromUtf8(u8"Not detected"), QString::fromUtf8(u8"Не определено"));
                m.insert(QString::fromUtf8(u8"Use the detected hardware recommendation when Automatic is selected"), QString::fromUtf8(u8"Использовать рекомендацию по оборудованию при выборе «Автоматически»"));
                m.insert(QString::fromUtf8(u8"Viewing distance"), QString::fromUtf8(u8"Дальность обзора"));
                m.insert(QString::fromUtf8(u8"Terrain"), QString::fromUtf8(u8"Ландшафт"));
                m.insert(QString::fromUtf8(u8"Terrain detail:"), QString::fromUtf8(u8"Детализация ландшафта:"));
                m.insert(QString::fromUtf8(u8"PBR quality:"), QString::fromUtf8(u8"Качество PBR:"));
                m.insert(QString::fromUtf8(u8"Shadow Distance Limit:"), QString::fromUtf8(u8"Дальность теней:"));
                m.insert(QString::fromUtf8(u8"Shadow Map Resolution:"), QString::fromUtf8(u8"Разрешение карты теней:"));
                m.insert(QString::fromUtf8(u8"Shadow Near Far Computation Method:"), QString::fromUtf8(u8"Расчёт ближней/дальней границы теней:"));
                m.insert(QString::fromUtf8(u8"Enable Player Shadows"), QString::fromUtf8(u8"Тени игрока"));
                m.insert(QString::fromUtf8(u8"Enable Actor Shadows"), QString::fromUtf8(u8"Тени NPC"));
                m.insert(QString::fromUtf8(u8"Enable Object Shadows"), QString::fromUtf8(u8"Тени объектов"));
                m.insert(QString::fromUtf8(u8"Enable Terrain Shadows"), QString::fromUtf8(u8"Тени ландшафта"));
                m.insert(QString::fromUtf8(u8"Enable Indoor Shadows"), QString::fromUtf8(u8"Тени в интерьерах"));
                m.insert(QString::fromUtf8(u8"Force shaders"), QString::fromUtf8(u8"Принудительные шейдеры"));
                m.insert(QString::fromUtf8(u8"Force per-pixel lighting"), QString::fromUtf8(u8"Попиксельное освещение"));
                m.insert(QString::fromUtf8(u8"OpenGL and scene optimizations"), QString::fromUtf8(u8"Оптимизации OpenGL и сцены"));
                m.insert(QString::fromUtf8(u8"OSG Patch"), QString::fromUtf8(u8"OSG Patch"));
                m.insert(QString::fromUtf8(u8"OSG threading model"), QString::fromUtf8(u8"Модель потоков OSG"));
                m.insert(QString::fromUtf8(u8"Renderer threading"), QString::fromUtf8(u8"Потоки рендера"));
                m.insert(QString::fromUtf8(u8"Streaming and physics"), QString::fromUtf8(u8"Стриминг и физика"));
                m.insert(QString::fromUtf8(u8"Cell preload threads"), QString::fromUtf8(u8"Потоки предзагрузки ячеек"));
                m.insert(QString::fromUtf8(u8"Background physics threads"), QString::fromUtf8(u8"Фоновые потоки физики"));
                m.insert(QString::fromUtf8(u8"Use object VBOs"), QString::fromUtf8(u8"Использовать VBO объектов"));
                m.insert(QString::fromUtf8(u8"Use object display lists"), QString::fromUtf8(u8"Использовать display lists объектов"));
                m.insert(QString::fromUtf8(u8"Allow OSG CPU affinity / thread pinning"), QString::fromUtf8(u8"Разрешить привязку потоков OSG к CPU"));
                m.insert(QString::fromUtf8(u8"Apply safe vendor-specific OpenGL and OpenSceneGraph optimizations"), QString::fromUtf8(u8"Применить безопасные оптимизации OpenGL/OpenSceneGraph для производителя GPU"));
                m.insert(QString::fromUtf8(u8"Enable occlusion culling"), QString::fromUtf8(u8"Включить occlusion culling"));
                m.insert(QString::fromUtf8(u8"Static occluders"), QString::fromUtf8(u8"Статические окклюдеры"));
                m.insert(QString::fromUtf8(u8"Terrain occluders"), QString::fromUtf8(u8"Окклюдеры ландшафта"));
                m.insert(QString::fromUtf8(u8"Active grid object paging"), QString::fromUtf8(u8"Object paging активной сетки"));
                m.insert(QString::fromUtf8(u8"Object paging min size"), QString::fromUtf8(u8"Минимальный размер object paging"));
                m.insert(QString::fromUtf8(u8"Defer physics AABB updates"), QString::fromUtf8(u8"Отложенные обновления AABB физики"));
                m.insert(QString::fromUtf8(u8"Build nav mesh for world geometry"), QString::fromUtf8(u8"Строить navmesh геометрии мира"));
                m.insert(QString::fromUtf8(u8"General"), QString::fromUtf8(u8"Общие"));
                m.insert(QString::fromUtf8(u8"Other"), QString::fromUtf8(u8"Другое"));
                m.insert(QString::fromUtf8(u8"Off"), QString::fromUtf8(u8"Выкл."));
                m.insert(QString::fromUtf8(u8"On"), QString::fromUtf8(u8"Вкл."));
                m.insert(QString::fromUtf8(u8"Simple"), QString::fromUtf8(u8"Простой"));
                m.insert(QString::fromUtf8(u8"Custom"), QString::fromUtf8(u8"Пользовательский"));
                m.insert(QString::fromUtf8(u8"Safe"), QString::fromUtf8(u8"Безопасный"));
                m.insert(QString::fromUtf8(u8"Normal"), QString::fromUtf8(u8"Обычный"));
                m.insert(QString::fromUtf8(u8"Compact (recommended)"), QString::fromUtf8(u8"Компактный (рекомендуется)"));
                m.insert(QString::fromUtf8(u8"Very compact"), QString::fromUtf8(u8"Очень компактный"));
                m.insert(QString::fromUtf8(u8"Character passage collision:"), QString::fromUtf8(u8"Коллизия прохода персонажей:"));
                m.insert(QString::fromUtf8(u8"Toggle sneak"), QString::fromUtf8(u8"Переключатель приседания"));
                m.insert(QString::fromUtf8(u8"Head bobbing in 1st person mode"), QString::fromUtf8(u8"Покачивание головы от первого лица"));
                m.insert(QString::fromUtf8(u8"Turn to movement direction"), QString::fromUtf8(u8"Поворот по направлению движения"));
                m.insert(QString::fromUtf8(u8"Smooth movement"), QString::fromUtf8(u8"Плавное движение"));
                m.insert(QString::fromUtf8(u8"View over the shoulder"), QString::fromUtf8(u8"Камера через плечо"));
                m.insert(QString::fromUtf8(u8"Default shoulder:"), QString::fromUtf8(u8"Плечо по умолчанию:"));
                m.insert(QString::fromUtf8(u8"Left"), QString::fromUtf8(u8"Левое"));
                m.insert(QString::fromUtf8(u8"Right"), QString::fromUtf8(u8"Правое"));
                m.insert(QString::fromUtf8(u8"Auto switch shoulder"), QString::fromUtf8(u8"Автопереключение плеча"));
                m.insert(QString::fromUtf8(u8"Preview if stand still"), QString::fromUtf8(u8"Предпросмотр при неподвижности"));
                m.insert(QString::fromUtf8(u8"Deferred preview rotation"), QString::fromUtf8(u8"Плавный возврат камеры после предпросмотра"));
                m.insert(QString::fromUtf8(u8"Grab cursor"), QString::fromUtf8(u8"Захватывать курсор"));
                m.insert(QString::fromUtf8(u8"Stretch menu background"), QString::fromUtf8(u8"Растягивать фон меню"));
                m.insert(QString::fromUtf8(u8"Allow container access in unloaded cells"), QString::fromUtf8(u8"Доступ к контейнерам в незагруженных ячейках"));
                m.insert(QString::fromUtf8(u8"Can loot during death animation"), QString::fromUtf8(u8"Можно обыскивать во время анимации смерти"));
                m.insert(QString::fromUtf8(u8"Enable graphic herbalism"), QString::fromUtf8(u8"Графический сбор растений"));
                m.insert(QString::fromUtf8(u8"Merchant equipping fix"), QString::fromUtf8(u8"Исправление экипировки торговцев"));
                m.insert(QString::fromUtf8(u8"Enchanted weapons are magical"), QString::fromUtf8(u8"Зачарованное оружие считается магическим"));
                m.insert(QString::fromUtf8(u8"Soulgem values rebalance"), QString::fromUtf8(u8"Перебалансировка стоимости камней душ"));
                m.insert(QString::fromUtf8(u8"Permanent barter disposition changes"), QString::fromUtf8(u8"Постоянное изменение отношения при торговле"));
                m.insert(QString::fromUtf8(u8"Racial variation in speed fix"), QString::fromUtf8(u8"Исправление расовой разницы скорости"));
                m.insert(QString::fromUtf8(u8"Uncapped Damage Fatigue"), QString::fromUtf8(u8"Неограниченный Damage Fatigue"));
                m.insert(QString::fromUtf8(u8"Swim upward correction"), QString::fromUtf8(u8"Коррекция плавания вверх"));
                m.insert(QString::fromUtf8(u8"Use magic item animation"), QString::fromUtf8(u8"Анимации магических предметов"));
                m.insert(QString::fromUtf8(u8"Trainers choose their training skills based on their base skill points"), QString::fromUtf8(u8"Тренеры выбирают навыки по базовым значениям"));
                m.insert(QString::fromUtf8(u8"Always allow stealing from knocked out actors"), QString::fromUtf8(u8"Разрешить кражу у оглушённых NPC"));
                m.insert(QString::fromUtf8(u8"Only appropriate ammunition bypasses normal weapon resistance"), QString::fromUtf8(u8"Только подходящие боеприпасы обходят сопротивление обычному оружию"));
                m.insert(QString::fromUtf8(u8"Affect werewolves"), QString::fromUtf8(u8"Применять к оборотням"));
                m.insert(QString::fromUtf8(u8"Do not affect werewolves"), QString::fromUtf8(u8"Не применять к оборотням"));
                m.insert(QString::fromUtf8(u8"Classic reflected Absorb spells behavior"), QString::fromUtf8(u8"Классическое отражение заклинаний Absorb"));
                m.insert(QString::fromUtf8(u8"Show effect duration"), QString::fromUtf8(u8"Показывать длительность эффектов"));
                m.insert(QString::fromUtf8(u8"Show enchant chance"), QString::fromUtf8(u8"Показывать шанс зачарования"));
                m.insert(QString::fromUtf8(u8"Show melee info"), QString::fromUtf8(u8"Показывать параметры оружия ближнего боя"));
                m.insert(QString::fromUtf8(u8"Show projectile damage"), QString::fromUtf8(u8"Показывать урон снарядов"));
                m.insert(QString::fromUtf8(u8"Change dialogue topic color"), QString::fromUtf8(u8"Менять цвет тем диалога"));
                m.insert(QString::fromUtf8(u8"Show owned:"), QString::fromUtf8(u8"Показывать принадлежность:"));
                m.insert(QString::fromUtf8(u8"Tool Tip Only"), QString::fromUtf8(u8"Только подсказка"));
                m.insert(QString::fromUtf8(u8"Crosshair Only"), QString::fromUtf8(u8"Только прицел"));
                m.insert(QString::fromUtf8(u8"Tool Tip and Crosshair"), QString::fromUtf8(u8"Подсказка и прицел"));
                m.insert(QString::fromUtf8(u8"Add \"Time Played\" to saves"), QString::fromUtf8(u8"Показывать время игры в сохранениях"));
                m.insert(QString::fromUtf8(u8"Morrowind Content Language"), QString::fromUtf8(u8"Язык контента Morrowind"));
                m.insert(QString::fromUtf8(u8"File to import settings from:"), QString::fromUtf8(u8"Файл для импорта настроек:"));
                m.insert(QString::fromUtf8(u8"Run &Settings Importer"), QString::fromUtf8(u8"Запустить &импорт настроек"));
                m.insert(QString::fromUtf8(u8"Run script after startup:"), QString::fromUtf8(u8"Запустить скрипт после старта:"));
                m.insert(QString::fromUtf8(u8"Browse..."), QString::fromUtf8(u8"Обзор..."));
                m.insert(QString::fromUtf8(u8"Browse…"), QString::fromUtf8(u8"Обзор..."));
                return m;
            }();
            return map;
        }
    };
}

#endif
