# ArenaMP portable build manifest
# Ordered entries are applied exactly as written.

[Build]
format=1
name="project NIRN 2.0"
data-path="Data files"
language="Russian"
complete=true
version=00001
build=00001
url="t.me/arena_mp"
url_check="mro1.myarena.site/build/check.ini"
url_update="mro1.myarena.site/build/update.zip"
url_win="mro1.myarena.site/build/ArenaMP-Windows-x64-main.zip"
url_linux="mro1.myarena.site/build/ArenaMP-Linux-x86_64-SteamDeck-main.tar.gz"
url_android="mro1.myarena.site/build/ArenaMP-arm64-client-server.apk"

[Server]
address="178.20.47.31"
port="25565"
use_alt_server=false
alt_adress=""
alt_port="25565"
vanilla-build-server=false

[Content]
content="Morrowind.esm"
content="Tribunal.esm"
content="Bloodmoon.esm"
content="GFM.esm"
content="Rebirth_Main.esm"
content="OAAB_Data.esm"
content="Tamriel_Data.esm"
content="TR_Mainland.esm"
content="Cyr_Main.esm"
content="Sky_Main.esm"
content="Wares-base.esm"
content="NOD_Core.esm"
content="TDoO_Main.esm"
content="Nirn_Core.ESP"
groundcover="Grass_Rebirth.omwaddon"
groundcover="Grass_TR.omwaddon"
groundcover="Grass_Cyr.omwaddon"
groundcover="Grass_Sky.omwaddon"

[Archives]
archive="Nirn_Pack_001.bsa"
archive="Nirn_Pack_002.bsa"
archive="Nirn_Pack_003.bsa"
archive="Nirn_Pack_004.bsa"
archive="Nirn_Pack_005.bsa"
archive="Nirn_Pack_006.bsa"
archive="Nirn_Pack_007.bsa"
archive="Nirn_Pack_008.bsa"
archive="Nirn_Pack_009.bsa"
archive="Nirn_Pack_010.bsa"
archive="Nirn_Pack_011.bsa"
archive="Nirn_Pack_012.bsa"
archive="Nirn_Pack_013.bsa"
archive="Nirn_Pack_014.bsa"
archive="Nirn_Pack_015.bsa"
