
color = {}

color.AliceBlue = "#F0F8FF"
color.AntiqueWhite = "#FAEBD7"
color.Aqua = "#00FFFF"
color.Aquamarine = "#7FFFD4"
color.Azure = "#F0FFFF"
color.Beige = "#F5F5DC"
color.Bisque = "#FFE4C4"
color.Black = "#000000"
color.BlanchedAlmond = "#FFEBCD"
color.Blue = "#0000FF"
color.BlueViolet = "#8A2BE2"
color.Brown = "#A52A2A"
color.BurlyWood = "#DEB887"
color.CadetBlue = "#5F9EA0"
color.Chartreuse = "#7FFF00"
color.Chocolate = "#D2691E"
color.Coral = "#FF7F50"
color.CornflowerBlue = "#6495ED"
color.Cornsilk = "#FFF8DC"
color.Crimson = "#DC143C"
color.Cyan = "#00FFFF"
color.DarkBlue = "#00008B"
color.DarkCyan = "#008B8B"
color.DarkGoldenRod = "#B8860B"
color.DarkGray = "#A9A9A9"
color.DarkGrey = "#A9A9A9"
color.DarkGreen = "#006400"
color.DarkKhaki = "#BDB76B"
color.DarkMagenta = "#8B008B"
color.DarkOliveGreen = "#556B2F"
color.DarkOrange = "#FF8C00"
color.DarkOrchid = "#9932CC"
color.DarkRed = "#8B0000"
color.DarkSalmon = "#E9967A"
color.DarkSeaGreen = "#8FBC8F"
color.DarkSlateBlue = "#483D8B"
color.DarkSlateGray = "#2F4F4F"
color.DarkSlateGrey = "#2F4F4F"
color.DarkTurquoise = "#00CED1"
color.DarkViolet = "#9400D3"
color.DeepPink = "#FF1493"
color.DeepSkyBlue = "#00BFFF"
color.DimGray = "#696969"
color.DimGrey = "#696969"
color.DodgerBlue = "#1E90FF"
color.FireBrick = "#B22222"
color.FloralWhite = "#FFFAF0"
color.ForestGreen = "#228B22"
color.Fuchsia = "#FF00FF"
color.Gainsboro = "#DCDCDC"
color.GhostWhite = "#F8F8FF"
color.Gold = "#FFD700"
color.GoldenRod = "#DAA520"
color.Gray = "#808080"
color.Grey = "#808080"
color.Green = "#008000"
color.GreenYellow = "#ADFF2F"
color.HoneyDew = "#F0FFF0"
color.HotPink = "#FF69B4"
color.IndianRed = "#CD5C5C"
color.Indigo = "#4B0082"
color.Ivory = "#FFFFF0"
color.Khaki = "#F0E68C"
color.Lavender = "#E6E6FA"
color.LavenderBlush = "#FFF0F5"
color.LawnGreen = "#7CFC00"
color.LemonChiffon = "#FFFACD"
color.LightBlue = "#ADD8E6"
color.LightCoral = "#F08080"
color.LightCyan = "#E0FFFF"
color.LightGoldenRodYellow = "#FAFAD2"
color.LightGray = "#D3D3D3"
color.LightGrey = "#D3D3D3"
color.LightGreen = "#90EE90"
color.LightPink = "#FFB6C1"
color.LightSalmon = "#FFA07A"
color.LightSeaGreen = "#20B2AA"
color.LightSkyBlue = "#87CEFA"
color.LightSlateGray = "#778899"
color.LightSlateGrey = "#778899"
color.LightSteelBlue = "#B0C4DE"
color.LightYellow = "#FFFFE0"
color.Lime = "#00FF00"
color.LimeGreen = "#32CD32"
color.Linen = "#FAF0E6"
color.Magenta = "#FF00FF"
color.Maroon = "#800000"
color.MediumAquaMarine = "#66CDAA"
color.MediumBlue = "#0000CD"
color.MediumOrchid = "#BA55D3"
color.MediumPurple = "#9370DB"
color.MediumSeaGreen = "#3CB371"
color.MediumSlateBlue = "#7B68EE"
color.MediumSpringGreen = "#00FA9A"
color.MediumTurquoise = "#48D1CC"
color.MediumVioletRed = "#C71585"
color.MidnightBlue = "#191970"
color.MintCream = "#F5FFFA"
color.MistyRose = "#FFE4E1"
color.Moccasin = "#FFE4B5"
color.NavajoWhite = "#FFDEAD"
color.Navy = "#000080"
color.OldLace = "#FDF5E6"
color.Olive = "#808000"
color.OliveDrab = "#6B8E23"
color.Orange = "#FFA500"
color.OrangeRed = "#FF4500"
color.Orchid = "#DA70D6"
color.PaleGoldenRod = "#EEE8AA"
color.PaleGreen = "#98FB98"
color.PaleTurquoise = "#AFEEEE"
color.PaleVioletRed = "#DB7093"
color.PapayaWhip = "#FFEFD5"
color.PeachPuff = "#FFDAB9"
color.Peru = "#CD853F"
color.Pink = "#FFC0CB"
color.Plum = "#DDA0DD"
color.PowderBlue = "#B0E0E6"
color.Purple = "#800080"
color.RebeccaPurple = "#663399"
color.Red = "#FF0000"
color.RosyBrown = "#BC8F8F"
color.RoyalBlue = "#4169E1"
color.SaddleBrown = "#8B4513"
color.Salmon = "#FA8072"
color.SandyBrown = "#F4A460"
color.SeaGreen = "#2E8B57"
color.SeaShell = "#FFF5EE"
color.Sienna = "#A0522D"
color.Silver = "#C0C0C0"
color.SkyBlue = "#87CEEB"
color.SlateBlue = "#6A5ACD"
color.SlateGray = "#708090"
color.SlateGrey = "#708090"
color.Snow = "#FFFAFA"
color.SpringGreen = "#00FF7F"
color.SteelBlue = "#4682B4"
color.Tan = "#D2B48C"
color.Teal = "#008080"
color.Thistle = "#D8BFD8"
color.Tomato = "#FF6347"
color.Turquoise = "#40E0D0"
color.Violet = "#EE82EE"
color.Wheat = "#F5DEB3"
color.White = "#FFFFFF"
color.WhiteSmoke = "#F5F5F5"
color.Yellow = "#FFFF00"
color.YellowGreen = "#9ACD32"

-- Темные оттенки
color.DarkAliceBlue = "#F0F8FF" -- Темный небесно-голубой
color.DarkAntiqueWhite = "#FAEBD7" -- Темный античный белый
color.DarkAqua = "#00B2B2" -- Темный аквамарин
color.DarkAquamarine = "#5EAE9C" -- Темный аквамарин
color.DarkAzure = "#A0D6D6" -- Темный азурный
color.DarkBeige = "#C5C5A0" -- Темный бежевый
color.DarkBisque = "#DDAF9A" -- Темный бисque
color.DarkBlue = "#00008B" -- Темный синий
color.DarkBlueViolet = "#6A0AD0" -- Темный синий фиолетовый
color.DarkBrown = "#7B3F3F" -- Темный коричневый
color.DarkBurlyWood = "#BFAF6B" -- Темный буковый
color.DarkCadetBlue = "#4B8B8B" -- Темный кадетский синий
color.DarkChartreuse = "#4DFF00" -- Темный шартрез
color.DarkChocolate = "#8B4513" -- Темный шоколад
color.DarkCoral = "#FF7F50" -- Темный коралл
color.DarkCornflowerBlue = "#3E64A0" -- Темный васильковый
color.DarkCornsilk = "#E8D3B7" -- Темный кукурузный шелк
color.DarkCrimson = "#9C1D3F" -- Темный малиновый
color.DarkCyan = "#008B8B" -- Темный циан
color.DarkDarkBlue = "#00004D" -- Очень темный синий
color.DarkDarkCyan = "#004D4D" -- Очень темный циан
color.DarkDarkGoldenRod = "#7B6D00" -- Очень темный золотарник
color.DarkDarkGray = "#4E4E4E" -- Очень темный серый
color.DarkDarkGrey = "#4E4E4E" -- Очень темный серый
color.DarkDarkGreen = "#003200" -- Очень темный зеленый
color.DarkDarkKhaki = "#7C7B00" -- Очень темный хаки
color.DarkDarkMagenta = "#5E005E" -- Очень темный пурпурный
color.DarkDarkOliveGreen = "#3B3B1F" -- Очень темный оливковый зеленый
color.DarkDarkOrange = "#CC6A00" -- Очень темный оранжевый
color.DarkDarkOrchid = "#6B006B" -- Очень темный орхидейный
color.DarkDarkRed = "#5E0000" -- Очень темный красный
color.DarkDarkSalmon = "#D48D7E" -- Очень темный лососевый
color.DarkDarkSeaGreen = "#3B7F3B" -- Очень темный морской зеленый
color.DarkDarkSlateBlue = "#2E2A4A" -- Очень темный темно-синий
color.DarkDarkSlateGray = "#1C1C1C" -- Очень темный темно-серый
color.DarkDarkSlateGrey = "#1C1C1C" -- Очень темный темно-серый
color.DarkDarkTurquoise = "#008B8B" -- Очень темный бирюзовый
color.DarkDarkViolet = "#6F006F" -- Очень темный фиолетовый
color.DarkDeepPink = "#C7006B" -- Очень темный насыщенно-розовый
color.DarkDeepSkyBlue = "#008BFF" -- Очень темный глубокий синий
color.DarkDimGray = "#4A4A4A" -- Очень темный тусклый серый
color.DarkDimGrey = "#4A4A4A" -- Очень темный тусклый серый
color.DarkDodgerBlue = "#005EB8" -- Темный голубой
color.DarkFireBrick = "#8B1C1C" -- Темный кирпичный
color.DarkFloralWhite = "#E0D6D0" -- Темный цветок
color.DarkForestGreen = "#1E4D1E" -- Темный лесной зеленый
color.DarkFuchsia = "#D400D4" -- Темный фуксия
color.DarkGainsboro = "#B0B0B0" -- Темный gainsboro
color.DarkGhostWhite = "#D0D0D0" -- Темный призрачный белый
color.DarkGold = "#B58E00" -- Темный золото
color.DarkGoldenRod = "#A88F00" -- Темный золотарник
color.DarkGray = "#606060" -- Темный серый
color.DarkGrey = "#606060" -- Темный серый
color.DarkGreen = "#004D00" -- Темный зеленый
color.DarkGreenYellow = "#8D8D00" -- Темный зеленый желтый
color.DarkHoneyDew = "#C3E8C3" -- Темный медовая роса
color.DarkHotPink = "#D7006B" -- Темный горячий розовый
color.DarkIndianRed = "#A02424" -- Темный индийский красный
color.DarkIndigo = "#3D004D" -- Темный индиго
color.DarkIvory = "#DADADA" -- Темный слоновая кость
color.DarkKhaki = "#7B7B00" -- Темный хаки
color.DarkLavender = "#B0B0E0" -- Темный лаванда
color.DarkLavenderBlush = "#E0B0C0" -- Темный розовый
color.DarkLawnGreen = "#5C7C00" -- Темный травяной зеленый
color.DarkLemonChiffon = "#D7D700" -- Темный лимонный
color.DarkLightBlue = "#005C8B" -- Темный светло-синий
color.DarkLightCoral = "#D03B3B" -- Темный светло-коралловый
color.DarkLightCyan = "#00B2B2" -- Темный светло-циан
color.DarkLightGoldenRodYellow = "#D7D700" -- Темный светлый золотарник
color.DarkLightGray = "#A2A2A2" -- Темный светло-серый
color.DarkLightGrey = "#A2A2A2" -- Темный светло-серый
color.DarkLightGreen = "#5DBB5D" -- Темный светло-зеленый
color.DarkLightPink = "#D45D5D" -- Темный светло-розовый
color.DarkLightSalmon = "#D4746D" -- Темный светло-лососевый
color.DarkLightSeaGreen = "#1B8888" -- Темный светло-морской зеленый
color.DarkLightSkyBlue = "#4C9EDD" -- Темный светло-небесно-синий
color.DarkLightSlateGray = "#5C5C5C" -- Темный светло-серый
color.DarkLightSlateGrey = "#5C5C5C" -- Темный светло-серый
color.DarkLightSteelBlue = "#8E9DCE" -- Темный светло-стальной синий
color.DarkLightYellow = "#D7D700" -- Темный светло-желтый
color.DarkLime = "#00CC00" -- Темный лайм
color.DarkLimeGreen = "#228B22" -- Темный лайм зеленый
color.DarkLinen = "#E2D6D0" -- Темный лен
color.DarkMagenta = "#A800A8" -- Темный пурпурный
color.DarkMaroon = "#5E0000" -- Темный бордовый
color.DarkMediumAquaMarine = "#4C9A8A" -- Темный средний аквамарин
color.DarkMediumBlue = "#00008B" -- Темный средний синий
color.DarkMediumOrchid = "#7A3D7A" -- Темный средний орхидейный
color.DarkMediumPurple = "#6A4E6A" -- Темный средний фиолетовый
color.DarkMediumSeaGreen = "#3D6B5D" -- Темный средний морской зеленый
color.DarkMediumSlateBlue = "#3B3D8B" -- Темный средний темно-синий
color.DarkMediumSpringGreen = "#00C7A0" -- Темный средний весенний зеленый
color.DarkMediumTurquoise = "#2B8B8B" -- Темный средний бирюзовый
color.DarkMediumVioletRed = "#B7007B" -- Темный средний фиолетово-красный
color.DarkMidnightBlue = "#2B2D4D" -- Темный полночный синий
color.DarkMintCream = "#A0DAD0" -- Темный мятный крем
color.DarkMistyRose = "#D0A1A1" -- Темный туманный розовый
color.DarkMoccasin = "#D3B5A0" -- Темный мокасин
color.DarkNavajoWhite = "#D9B000" -- Темный навахо белый
color.DarkNavy = "#000060" -- Темный темно-синий
color.DarkOldLace = "#E2D6D0" -- Темный старый кружевной
color.DarkOlive = "#4D4D00" -- Темный оливковый
color.DarkOliveDrab = "#4E6B4E" -- Темный оливковый зеленый
color.DarkOrange = "#A75D00" -- Темный оранжевый
color.DarkOrangeRed = "#A52A00" -- Темный оранжевый красный
color.DarkOrchid = "#8A00A8" -- Темный орхидейный
color.DarkPaleGoldenRod = "#D7D700" -- Темный бледный золотарник
color.DarkPaleGreen = "#6BBF6B" -- Темный бледно-зеленый
color.DarkPaleTurquoise = "#8BD3D3" -- Темный бледно-бирюзовый
color.DarkPaleVioletRed = "#A000A0" -- Темный бледный фиолетово-красный
color.DarkPapayaWhip = "#E6D3A0" -- Темный папайя белый
color.DarkPeachPuff = "#E3B1A0" -- Темный персиковый
color.DarkPeru = "#A65E3D" -- Темный перу
color.DarkPink = "#D7006B" -- Темный розовый
color.DarkPlum = "#8E3D8E" -- Темный слива
color.DarkPowderBlue = "#003C5B" -- Темный порошковый синий
color.DarkPurple = "#4B004B" -- Темный фиолетовый
color.DarkRebeccaPurple = "#4B1E4B" -- Темный рекабека фиолетовый
color.DarkRed = "#A80000" -- Темный красный
color.DarkRosyBrown = "#6C3D3D" -- Темный розовато-коричневый
color.DarkRoyalBlue = "#00006B" -- Темный королевский синий
color.DarkSaddleBrown = "#5C3D2D" -- Темный седловой коричневый
color.DarkSalmon = "#D76B6B" -- Темный лососевый
color.DarkSandyBrown = "#D49368" -- Темный песчаный коричневый
color.DarkSeaGreen = "#4C8B4C" -- Темный морской зеленый
color.DarkSeaShell = "#E1B8B8" -- Темный морской ракушка
color.DarkSienna = "#6B3D3D" -- Темный сиенна
color.DarkSilver = "#A6A6A6" -- Темный серебряный
color.DarkSkyBlue = "#0066CC" -- Темный небесно-голубой
color.DarkSlateBlue = "#3B3B5C" -- Темный темно-синий
color.DarkSlateGray = "#2B2B2B" -- Темный темно-серый
color.DarkSlateGrey = "#2B2B2B" -- Темный темно-серый
color.DarkSnow = "#E6E6E6" -- Темный снег
color.DarkSpringGreen = "#00A3A0" -- Темный весенний зеленый
color.DarkSteelBlue = "#2B4B4B" -- Темный стальной синий
color.DarkTan = "#7B4F2B" -- Темный загар
color.DarkTeal = "#004D4D" -- Темный бирюзовый
color.DarkThistle = "#D3A8D3" -- Темный чертополох
color.DarkTomato = "#A60000" -- Темный томат
color.DarkTurquoise = "#008B8B" -- Темный бирюзовый
color.DarkViolet = "#5C00A6" -- Темный фиолетовый
color.DarkWheat = "#D7B74F" -- Темный пшеница
color.DarkWhite = "#E8E8E8" -- Темный белый
color.DarkWhiteSmoke = "#E0E0E0" -- Темный дымчатый белый
color.DarkYellow = "#A5A500" -- Темный желтый
color.DarkYellowGreen = "#6D6D00" -- Темный желто-зеленый

color.Default = color.White
color.Error = color.Red
color.Warning = color.GoldenRod
color.GreenText = "#789922"

-- ArenaMP compatibility aliases used by the legacy RP chat/list scripts.
-- Keep both historical spellings so old server data and future ports are safe.
color.Goldenrod = color.GoldenRod
color.DarkGoldenrod = color.DarkGoldenRod
color.Honeydew = color.HoneyDew
color.DarkHoneydew = color.DarkHoneyDew
color.PaleGoldenrod = color.PaleGoldenRod
color.DarkPaleGoldenrod = color.DarkPaleGoldenRod
color.Mint = color.MintCream
color.DarkMint = color.DarkMintCream

return color